### ISSUE TITLE
Loading from a local image isn't working

### ISSUE THREAD

**Issue by DamianMullins** [ashleynolan/handlebars-helper-inlineSVG#1]
When I use the example given in the readme of `{{inlineSVG "img/test.svg"}}` (looking up an image from within my project), I get an error of 

```bash
"{{inlineSVG}} helper: . Error: Cannot find module '/img/test.svg' from '.../node_modules/handlebars-helper-inlinesvg/dist'"
```
It looks like it is jumping straight to looking within the `node_modules` directory and not performing a local lookup?

**Comment by DamianMullins** [comment]
My bad, the issue was in my code! 😳

**Comment by isellsoap** [comment]
@DamianMullins As I’m facing the same issue: what was the issue in your code?

**Comment by DamianMullins** [comment]
Not what you want to hear, but I've forgotten what my mistake was 😒  If you add a bit of context about your particular issue here I may be able to help you out though?

**Comment by isellsoap** [comment]
I managed to find the solution. The path is relative to where the .md file is located. That wasn’t clear to me. :+1:

**Comment by rhys-vdw** [comment]
What `.md` file? Looking at the source it seems it _must_ search from the `handlebars-helper-inlinesvg/dist` due to the way resolve works.
